version: "3.9"
services:
  go:
    container_name: ent-with-echo
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
